name: CI
on:
  push: { branches: ['+([0-9])?(.{+([0-9]),x}).x', 'master','main', 'next', 'next-major', 'beta', 'alpha'] }
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Plugins
      run: npm install @semantic-release/git @semantic-release/changelog -D
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
