name: CI
on:
  push: { branches: ['+([0-9])?(.{+([0-9]),x}).x', 'master','main', 'next', 'next-major', 'beta', 'alpha'] }
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Pull modules
      run: npx -p @semantic-release/changelog -p @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
